#creating container of mongo:3.6.4
FROM mongo:3.6.4

#RUN sh -c 'mongoimport --uri="mongodb://test_mongodb:27017/animal_db" -c colln  --drop' < d2.json

#RUN mongoimport  --uri='mongodb://172.19.0.2:27017/animal_db' --type='json'  --file='d2.json'

#RUN mongoimport --jsonArray --password='pass' --host='mongodb'--port=27017 --db='animal_db' --username='root'  --collection='colln' --file='d2.json'
